def iniList():
	# Section, Item, Object Name
	iniList = []
	iniList.append(['EMC', 'VERSION', 'version'])
	iniList.append(['EMC', 'MACHINE', 'configName'])
	iniList.append(['JOINT_0', 'STEPLEN', 'stepTime_0'])
	iniList.append(['JOINT_0', 'STEPSPACE', 'stepSpace_0'])
	iniList.append(['JOINT_0', 'DIRSETUP', 'dirSetup_0'])
	iniList.append(['JOINT_0', 'DIRHOLD', 'dirHold_0'])
	iniList.append(['JOINT_0', 'MIN_LIMIT', 'minLimit_0'])
	iniList.append(['JOINT_0', 'MAX_LIMIT', 'maxLimit_0'])
	iniList.append(['JOINT_0', 'MAX_VELOCITY', 'maxVelocity_0'])
	iniList.append(['JOINT_0', 'MAX_ACCELERATION', 'maxAccel_0'])
	iniList.append(['JOINT_0', 'SCALE', 'scale_0'])
	iniList.append(['JOINT_0', 'HOME', 'home_0'])
	iniList.append(['JOINT_0', 'HOME_OFFSET', 'homeOffset_0'])
	iniList.append(['JOINT_0', 'HOME_SEARCH_VEL', 'homeSearchVel_0'])
	iniList.append(['JOINT_0', 'HOME_LATCH_VEL', 'homeLatchVel_0'])
	iniList.append(['JOINT_0', 'HOME_USE_INDEX', 'homeUseIndex_0'])
	iniList.append(['JOINT_0', 'HOME_IGNORE_LIMITS', 'homeIgnoreLimits_0'])

	iniList.append(['JOINT_1', 'STEPLEN', 'stepTime_1'])
	iniList.append(['JOINT_1', 'STEPSPACE', 'stepSpace_1'])
	iniList.append(['JOINT_1', 'DIRSETUP', 'dirSetup_1'])
	iniList.append(['JOINT_1', 'DIRHOLD', 'dirHold_1'])
	iniList.append(['JOINT_1', 'MIN_LIMIT', 'minLimit_1'])
	iniList.append(['JOINT_1', 'MAX_LIMIT', 'maxLimit_1'])
	iniList.append(['JOINT_1', 'MAX_VELOCITY', 'maxVelocity_1'])
	iniList.append(['JOINT_1', 'MAX_ACCELERATION', 'maxAccel_1'])
	iniList.append(['JOINT_1', 'SCALE', 'scale_1'])
	iniList.append(['JOINT_1', 'HOME', 'home_1'])
	iniList.append(['JOINT_1', 'HOME_OFFSET', 'homeOffset_1'])
	iniList.append(['JOINT_1', 'HOME_SEARCH_VEL', 'homeSearchVel_1'])
	iniList.append(['JOINT_1', 'HOME_LATCH_VEL', 'homeLatchVel_1'])
	iniList.append(['JOINT_1', 'HOME_USE_INDEX', 'homeUseIndex_1'])
	iniList.append(['JOINT_1', 'HOME_IGNORE_LIMITS', 'homeIgnoreLimits_1'])

	iniList.append(['JOINT_2', 'STEPLEN', 'stepTime_2'])
	iniList.append(['JOINT_2', 'STEPSPACE', 'stepSpace_2'])
	iniList.append(['JOINT_2', 'DIRSETUP', 'dirSetup_2'])
	iniList.append(['JOINT_2', 'DIRHOLD', 'dirHold_2'])
	iniList.append(['JOINT_2', 'MIN_LIMIT', 'minLimit_2'])
	iniList.append(['JOINT_2', 'MAX_LIMIT', 'maxLimit_2'])
	iniList.append(['JOINT_2', 'MAX_VELOCITY', 'maxVelocity_2'])
	iniList.append(['JOINT_2', 'MAX_ACCELERATION', 'maxAccel_2'])
	iniList.append(['JOINT_2', 'SCALE', 'scale_2'])
	iniList.append(['JOINT_2', 'HOME', 'home_2'])
	iniList.append(['JOINT_2', 'HOME_OFFSET', 'homeOffset_2'])
	iniList.append(['JOINT_2', 'HOME_SEARCH_VEL', 'homeSearchVel_2'])
	iniList.append(['JOINT_2', 'HOME_LATCH_VEL', 'homeLatchVel_2'])
	iniList.append(['JOINT_2', 'HOME_USE_INDEX', 'homeUseIndex_2'])
	iniList.append(['JOINT_2', 'HOME_IGNORE_LIMITS', 'homeIgnoreLimits_2'])

	iniList.append(['JOINT_3', 'STEPLEN', 'stepTime_3'])
	iniList.append(['JOINT_3', 'STEPSPACE', 'stepSpace_3'])
	iniList.append(['JOINT_3', 'DIRSETUP', 'dirSetup_3'])
	iniList.append(['JOINT_3', 'DIRHOLD', 'dirHold_3'])
	iniList.append(['JOINT_3', 'MIN_LIMIT', 'minLimit_3'])
	iniList.append(['JOINT_3', 'MAX_LIMIT', 'maxLimit_3'])
	iniList.append(['JOINT_3', 'MAX_VELOCITY', 'maxVelocity_3'])
	iniList.append(['JOINT_3', 'MAX_ACCELERATION', 'maxAccel_3'])
	iniList.append(['JOINT_3', 'SCALE', 'scale_3'])
	iniList.append(['JOINT_3', 'HOME', 'home_3'])
	iniList.append(['JOINT_3', 'HOME_OFFSET', 'homeOffset_3'])
	iniList.append(['JOINT_3', 'HOME_SEARCH_VEL', 'homeSearchVel_3'])
	iniList.append(['JOINT_3', 'HOME_LATCH_VEL', 'homeLatchVel_3'])
	iniList.append(['JOINT_3', 'HOME_USE_INDEX', 'homeUseIndex_3'])
	iniList.append(['JOINT_3', 'HOME_IGNORE_LIMITS', 'homeIgnoreLimits_3'])

	iniList.append(['JOINT_4', 'STEPLEN', 'stepTime_4'])
	iniList.append(['JOINT_4', 'STEPSPACE', 'stepSpace_4'])
	iniList.append(['JOINT_4', 'DIRSETUP', 'dirSetup_4'])
	iniList.append(['JOINT_4', 'DIRHOLD', 'dirHold_4'])
	iniList.append(['JOINT_4', 'MIN_LIMIT', 'minLimit_4'])
	iniList.append(['JOINT_4', 'MAX_LIMIT', 'maxLimit_4'])
	iniList.append(['JOINT_4', 'MAX_VELOCITY', 'maxVelocity_4'])
	iniList.append(['JOINT_4', 'MAX_ACCELERATION', 'maxAccel_4'])
	iniList.append(['JOINT_4', 'SCALE', 'scale_4'])
	iniList.append(['JOINT_4', 'HOME', 'home_4'])
	iniList.append(['JOINT_4', 'HOME_OFFSET', 'homeOffset_4'])
	iniList.append(['JOINT_4', 'HOME_SEARCH_VEL', 'homeSearchVel_4'])
	iniList.append(['JOINT_4', 'HOME_LATCH_VEL', 'homeLatchVel_4'])
	iniList.append(['JOINT_4', 'HOME_USE_INDEX', 'homeUseIndex_4'])
	iniList.append(['JOINT_4', 'HOME_IGNORE_LIMITS', 'homeIgnoreLimits_40'])

	return iniList

#iniList.append(['', '', ''])
